name: Dockerfile Parser

on:
  push:
    branches:
      - main

jobs:
  parse_dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Create a requirements.txt file with "re" dependency

      - name: Run Dockerfile Parser
        run: |
          python your_script.py  # Replace with the actual script filename

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update parsed Dockerfile"
          git push
